// Project Sword & Gun Copyright © 2021 Kevin Poretti

#pragma once

#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "SwordNGun/SNGTypes.h"

#include "SNGEventBlueprintLibrary.generated.h"

/**
 * 
 */
UCLASS()
class SWORDNGUN_API USNGEventBlueprintLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

	UFUNCTION(BlueprintCallable)
	static FSNGCharacterCommandData GetEventDataAsCommandData(FSNGEvent Event);

	UFUNCTION(BlueprintCallable)
	static FSNGDamageData GetEventDataAsDamageData(FSNGEvent Event);
};
