// Project Sword & Gun Copyright © 2021 Kevin Poretti


#include "Weapons/SNGWeaponBase.h"

// Sets default values
ASNGWeaponBase::ASNGWeaponBase()
{
 	// Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;

	WeaponMesh = CreateDefaultSubobject<USkeletalMeshComponent>(TEXT("WeaponMesh"));
	WeaponMesh->SetupAttachment(RootComponent);
}

float ASNGWeaponBase::CalculateWeaponDamage()
{
	return 0.0f;
}

void ASNGWeaponBase::SetVisibility(bool IsVisible)
{
	WeaponMesh->SetVisibility(IsVisible);
}

void ASNGWeaponBase::PlayImpactEffects(EPhysicalSurface SurfaceType, FVector ImpactPoint)
{
}

// Called when the game starts or when spawned
void ASNGWeaponBase::BeginPlay()
{
	Super::BeginPlay();
	
}

// Called every frame
void ASNGWeaponBase::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

}

