// Project Sword & Gun Copyright © 2021 Kevin Poretti

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Character.h"
#include "SNGCharacterBase.generated.h"

UCLASS()
class SWORDNGUN_API ASNGCharacterBase : public ACharacter
{
	GENERATED_BODY()

public:
	// Sets default values for this character's properties
	ASNGCharacterBase();

	UFUNCTION(BlueprintCallable)
	void SetIgnoreMovementInput(bool IsIgnored);

	UFUNCTION(BlueprintCallable)
	void SetCanCancel(bool CanCancel);
	
	UFUNCTION(BlueprintGetter)
	bool CanCancel();
	
protected:

	UPROPERTY(BlueprintReadOnly)
	bool bCanCancel;
};
